message(STATUS "Toolchain loaded: unix-libc++.cmake")
if(EXISTS "${CMAKE_SOURCE_DIR}/build/conan_toolchain.cmake")
    include("${CMAKE_SOURCE_DIR}/build/conan_toolchain.cmake")
endif()

if (LINUX)
    if (NOT DEFINED LLVM_LIB_SET)
        message(STATUS "-- Set libc++ runtime")
        set(LLVM_LIB_SET 1)
        set(CMAKE_CXX_FLAGS "-stdlib=libc++ ${CMAKE_CXX_FLAGS}")
    endif()
endif()